### ISSUE TITLE
DeepEqual() が欲しい

### ISSUE THREAD

**Issue by logica0419** [youta-t/its#59]
structの比較にstructerを使うべきなのは思想としてそうなのですが、全く同じ内容であることを単純に比較したい時、`reflect.DeepEqual()`をベースにした比較ができると手間が省けて楽だと思いました

カスタマイズしたいときは`structer`、脳死でやりたいときは`DeepEqual()`という感じです

**Comment by youta-t** [comment]
なるほど、これは struct に `slice` や `map` を含むようなユースケースで、単に `reflect.DeepEqual()` で十分なことがある、というお話ですね？

**Comment by logica0419** [comment]
そうですね、僕が作っているこのライブラリのここがそうです
GIFのリサイジングライブラリなのですが、生成された`*gif.GIF`と欲しい結果のGIF画像を開いてパースした`*gif.GIF`が一緒なことを確認しています
https://github.com/logica0419/resigif/blob/main/resigif_test.go#L160

**Comment by logica0419** [comment]
良ければContributeもしたいなと思っているので、もしyoutaさんが「入れても良いな」となったらPR出させていただけると嬉しいです！

**Comment by youta-t** [comment]
なるほど、確かにそのユースケースなら `*gif.GIF` は opaque なものとして扱ってしまって、DeepEqual で比較したほうが通りが良さそうですね。

Contribute は歓迎します。 `general.go` に追記する形で良いはずです。

**Comment by youta-t** [comment]
Contribute ありがとうございました 🙇
